### ISSUE TITLE
Uncaught Exception: NoClassDefFoundError - ghidra/framework/plugintool/util/OptionService

### ISSUE THREAD

**Issue by 20urc3** [nccgroup/Cartographer#3]
Following the previous issue I have run some tests.
This problems occurs when trying to display the Windows "Code Coverage"

```
Uncaught Exception: NoClassDefFoundError - ghidra/framework/plugintool/util/OptionService

ghidra/framework/plugintool/util/OptionsService
java.lang.NoClassDefFoundError: ghidra/framework/plugintool/util/OptionsService
	at cartographer.CartographerProvider$2.isEnabledForContext(CartographerProvider.java:396)
	at docking.ComponentPlaceholder.contextChanged(ComponentPlaceholder.java:538)
	at docking.ComponentPlaceholder.lambda$requestFocus$0(ComponentPlaceholder.java:293)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: ghidra.framework.plugintool.util.OptionsService
	... 16 more

---------------------------------------------------
Build Date: 2023-Sep-28 1301 EDT
Ghidra Version: 10.4
Java Home: C:\Program Files\Java\jdk-17
JVM Version: Oracle Corporation 17.0.9
OS: Windows 10 10.0 amd64
Workstation: DESKTOP
```

**Comment by 20urc3** [comment]
After a while the error results in:

```
PDF.exe was closed due to an unrecoverable error!

Such failures are generally due to an IO Error caused
by the local filesystem or server.
---------------------------------------------------
Build Date: 2023-Sep-28 1301 EDT
Ghidra Version: 10.4
Java Home: C:\Program Files\Java\jdk-17
JVM Version: Oracle Corporation 17.0.9
OS: Windows 10 10.0 amd64
Workstation: DESKTOP
```
